# PIAIC Muneeb Ahmed Ayub

In [1]:
import numpy as np

## 1. np.array

In [2]:
arr = np.array([1,2,3,4,5,6,7,8,9])
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

## 2. np.arange

In [3]:
arr1 = np.arange(3*5)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## 3. reshape

In [4]:
arr1 = arr1.reshape(3,5)
arr1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

## 4. shape

In [5]:
arr1.shape

(3, 5)

## 5.ndim

In [6]:
arr1.ndim

2

## 6.dtype

In [7]:
arr1.dtype

dtype('int32')

## 7.itemsize

In [8]:
arr1.itemsize

4

## 8.type

In [9]:
type(arr1)

numpy.ndarray

## 9. zeros

In [10]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

## 10. ones

In [11]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

## 11. empty

In [12]:
np.empty((3,3))

array([[0.00e+000, 0.00e+000, 0.00e+000],
       [0.00e+000, 0.00e+000, 1.52e-321],
       [0.00e+000, 0.00e+000, 0.00e+000]])

## 12. linspace

In [13]:
np.linspace(0,np.pi,10)

array([0.        , 0.34906585, 0.6981317 , 1.04719755, 1.3962634 ,
       1.74532925, 2.0943951 , 2.44346095, 2.7925268 , 3.14159265])

## 13. Trignometric Functions

In [16]:
np.sin(arr1)

array([[ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ],
       [-0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849],
       [-0.54402111, -0.99999021, -0.53657292,  0.42016704,  0.99060736]])

## 14. sqrt

In [17]:
np.sqrt(arr1)

array([[0.        , 1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ],
       [3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739]])

## 15. power

In [19]:
np.power(arr1, 2)

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196]], dtype=int32)

## 16. random

In [21]:
arr2 = np.random.randn(3,4)
arr2

array([[-0.05530503,  0.5163311 ,  1.16562536, -0.41775414],
       [ 0.53381256,  0.40887423, -1.99154767,  0.44099472],
       [-0.82469894, -0.36868175, -0.24027608, -0.93031741]])

## 17. sum of each row

In [22]:
arr2.sum(axis=1)

array([ 1.20889729, -0.60786616, -2.36397418])

## 18. minimum of each column

In [23]:
arr2.min(axis=0)

array([-0.82469894, -0.36868175, -1.99154767, -0.93031741])

## 19. comulative sum of each row

In [24]:
arr2.cumsum(axis=1)

array([[-0.05530503,  0.46102607,  1.62665142,  1.20889729],
       [ 0.53381256,  0.94268679, -1.04886088, -0.60786616],
       [-0.82469894, -1.19338069, -1.43365677, -2.36397418]])

## 20. making square of ones

In [31]:
arr3 = np.ones((4,4))
arr3[1:-1,1:-1] = 0
arr3

array([[1., 1., 1., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 1., 1., 1.]])

## 21. to perform operations on each element of array

In [33]:
for element in arr3.flat:
    print(element)

1.0
1.0
1.0
1.0
1.0
0.0
0.0
1.0
1.0
0.0
0.0
1.0
1.0
1.0
1.0
1.0


## 22. sort all elements

In [35]:
arr2.sort()
arr2

array([[-0.41775414, -0.05530503,  0.5163311 ,  1.16562536],
       [-1.99154767,  0.40887423,  0.44099472,  0.53381256],
       [-0.93031741, -0.82469894, -0.36868175, -0.24027608]])

## 23. make array of unique elements

In [36]:
np.unique([2,3,2,5,5,3])

array([2, 3, 5])

## 24. floor

In [40]:
a = np.floor(arr2)
a

array([[-1., -1.,  0.,  1.],
       [-2.,  0.,  0.,  0.],
       [-1., -1., -1., -1.]])

## 25. ravel

In [41]:
a.ravel()

array([-1., -1.,  0.,  1., -2.,  0.,  0.,  0., -1., -1., -1., -1.])

## 26. T (transposed)

In [43]:
a.T

array([[-1., -2., -1.],
       [-1.,  0., -1.],
       [ 0.,  0., -1.],
       [ 1.,  0., -1.]])

## 27. resize

In [45]:
a.resize((6,2))
a

array([[-1., -1.],
       [ 0.,  1.],
       [-2.,  0.],
       [ 0.,  0.],
       [-1., -1.],
       [-1., -1.]])

## 28. vertical stack

In [54]:
x=np.floor(10*np.random.randn(3,3))
x

array([[ -6.,  -8.,  -4.],
       [-25.,   7.,  11.],
       [-15.,  -6.,  13.]])

In [55]:
y=np.floor(10*np.random.randn(3,3))
y

array([[ 11.,  34.,  -7.],
       [ -3., -18., -14.],
       [ -2.,   5., -12.]])

In [56]:
np.vstack((x,y))

array([[ -6.,  -8.,  -4.],
       [-25.,   7.,  11.],
       [-15.,  -6.,  13.],
       [ 11.,  34.,  -7.],
       [ -3., -18., -14.],
       [ -2.,   5., -12.]])

## 29. horizontal stack

In [57]:
np.hstack((x,y))

array([[ -6.,  -8.,  -4.,  11.,  34.,  -7.],
       [-25.,   7.,  11.,  -3., -18., -14.],
       [-15.,  -6.,  13.,  -2.,   5., -12.]])

In [58]:
np.column_stack((x,y))

array([[ -6.,  -8.,  -4.,  11.,  34.,  -7.],
       [-25.,   7.,  11.,  -3., -18., -14.],
       [-15.,  -6.,  13.,  -2.,   5., -12.]])

## 30. horizontal split

In [60]:
x = np.arange(2*12).reshape(2,12)
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [62]:
np.hsplit(x,2)

[array([[ 0,  1,  2,  3,  4,  5],
        [12, 13, 14, 15, 16, 17]]),
 array([[ 6,  7,  8,  9, 10, 11],
        [18, 19, 20, 21, 22, 23]])]

## 31. view

In [65]:
a = x.view()
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

## 32.copy

In [69]:
b = x.copy()
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

## 33. save array in file

In [71]:
x = np.arange(3*4).reshape(3,4)
y = np.arange(4*3).reshape(4,3)

In [72]:
np.save("testx", x)

## 34. save multiple arrays in file

In [85]:
np.savez("testxy", x=x, y=y)

## 35. load arrays from file

In [86]:
loadx = np.load("testx.npy")
loadx

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [87]:
loadxy = np.load("testxy.npz")

In [88]:
loadxy

In [89]:
loadxy['x']

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [91]:
loadxy['y']

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

## 36. dot product

In [92]:
x.dot(y)

array([[ 42,  48,  54],
       [114, 136, 158],
       [186, 224, 262]])

## 37. trace

In [93]:
x.trace()

15

## 38. where

In [95]:
np.where(x==5, 100, x)

array([[  0,   1,   2,   3],
       [  4, 100,   6,   7],
       [  8,   9,  10,  11]])

## 39. make ones in diagonal

In [96]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## 40. ix_() function

In [97]:
a = np.array([3,5,2,6])
b = np.array([1,4,6,8,4,2,4])
c = np.array([4,1,5])
ax,bx,cx = np.ix_(a,b,c)

In [98]:
ax

array([[[3]],

       [[5]],

       [[2]],

       [[6]]])

In [99]:
bx

array([[[1],
        [4],
        [6],
        [8],
        [4],
        [2],
        [4]]])

In [100]:
cx

array([[[4, 1, 5]]])

## 41. matrix inverse

In [103]:
a = np.arange(2*2).reshape(2,2)
np.linalg.inv(a)

array([[-1.5,  0.5],
       [ 1. ,  0. ]])

## 42. matrix product

In [104]:
a @ a

array([[ 2,  3],
       [ 6, 11]])

## 43. eigen values

In [107]:
np.linalg.eig(a)

(array([-0.56155281,  3.56155281]),
 array([[-0.87192821, -0.27032301],
        [ 0.48963374, -0.96276969]]))

## 44. imag

In [110]:
a.imag

array([[0, 0],
       [0, 0]])

## 45. tobytes

In [112]:
a.tobytes()

b'\x00\x00\x00\x00\x01\x00\x00\x00\x02\x00\x00\x00\x03\x00\x00\x00'

## 46. reverse 1d array

In [113]:
b = np.array([1,2,3,4,5,6])
np.flip(b)

array([6, 5, 4, 3, 2, 1])

## 47. reverse 2d array

In [114]:
a = np.arange(3*3).reshape(3,3)
np.flip(a)

array([[8, 7, 6],
       [5, 4, 3],
       [2, 1, 0]])

In [115]:
np.flip(a, axis=0)

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [116]:
np.flip(a, axis=1)

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

## 48. expand row dimensions

In [120]:
np.expand_dims(a, axis=1)

array([[[0, 1, 2]],

       [[3, 4, 5]],

       [[6, 7, 8]]])

## 49. expand column dimensions

In [121]:
np.expand_dims(a, axis=0)

array([[[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]])

## 50. numpy version and configuration

In [124]:
np.__version__, np.show_config()

blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Personal/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Personal/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Personal/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Personal/anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Personal/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Personal/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Personal/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Personal/anaconda3\\Library\\include']


('1.19.2', None)

In [ ]:
0